services:
  crm_app:
    build: .
    expose:
      - "5000"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./key.pem:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - crm_app
    networks:
      - webnet

networks:
  webnet:
